<?php
/**
 * acf-setup.php
 */

// return if this is dev environment
if ( WP_ENV === 'development' ) {
  return;
}

// hide field group menu from users
if ( wp_get_current_user()->user_login !== 'sean' ) {
  define( 'ACF_LITE' , true );
}

/*
ACF field groups
 */
// export field export code here:
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
  'key' => 'group_5920752df41bd',
  'title' => 'Home Page Fields',
  'fields' => array (
    array (
      'key' => 'field_5920753c27efe',
      'label' => 'Home Sections',
      'name' => 'home_sections',
      'type' => 'flexible_content',
      'instructions' => 'Add home sections by clicking "Add Section" below.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'button_label' => 'Add Section',
      'min' => 1,
      'max' => '',
      'layouts' => array (
        array (
          'key' => '592075503041c',
          'name' => 'map_section',
          'label' => 'Map Section',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_592842506e7ae',
              'label' => 'Section Title',
              'name' => 'section_title',
              'type' => 'text',
              'instructions' => 'Enter a title for the section.',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_59284337afbf9',
              'label' => 'Map Locations',
              'name' => '',
              'type' => 'message',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'message' => 'Map locations are added by clicking <em>Locations > Add New</em> on the left-hand side of the dashboard.',
              'new_lines' => 'wpautop',
              'esc_html' => 0,
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '592843016e7b0',
          'name' => 'difference_section',
          'label' => 'Difference Section',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_592843016e7b1',
              'label' => 'Section Title',
              'name' => 'section_title',
              'type' => 'text',
              'instructions' => 'Enter a title for the section.',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_592847cfc9b1c',
              'label' => 'Steps Sections',
              'name' => 'steps_sections',
              'type' => 'repeater',
              'instructions' => 'Add a steps section by clicking "Add Steps" below.',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'collapsed' => '',
              'min' => 0,
              'max' => 0,
              'layout' => 'row',
              'button_label' => 'Add Steps',
              'sub_fields' => array (
                array (
                  'key' => 'field_59284893c9b1d',
                  'label' => 'Step Title',
                  'name' => 'step_title',
                  'type' => 'text',
                  'instructions' => 'Enter a title for the differences step.',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                ),
                array (
                  'key' => 'field_592848a4c9b1e',
                  'label' => 'Step Photo',
                  'name' => 'step_photo',
                  'type' => 'image',
                  'instructions' => 'Upload a photo for the differences step.',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'return_format' => 'array',
                  'preview_size' => 'thumbnail',
                  'library' => 'all',
                  'min_width' => 300,
                  'min_height' => 300,
                  'min_size' => '',
                  'max_width' => '',
                  'max_height' => '',
                  'max_size' => '',
                  'mime_types' => 'gif,jpg,jpeg,png,webp',
                ),
              ),
            ),
            array (
              'key' => 'field_59284905c9b1f',
              'label' => 'Product Photo',
              'name' => 'product_photo',
              'type' => 'image',
              'instructions' => 'Upload a photo of the product to appear at the bottom of the differences section.',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'return_format' => 'array',
              'preview_size' => 'thumbnail',
              'library' => 'all',
              'min_width' => '',
              'min_height' => '',
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => '',
              'mime_types' => 'gif,jpg,jpeg,png,webp',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '5928430c6e7b2',
          'name' => 'recipe_section',
          'label' => 'Recipe Section',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_5928430c6e7b3',
              'label' => 'Section Title',
              'name' => 'section_title',
              'type' => 'text',
              'instructions' => 'Enter a title for the section.',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_5928494cc9b20',
              'label' => 'Recipes',
              'name' => 'recipes',
              'type' => 'relationship',
              'instructions' => 'Select recipes to appear as tiles in the recipe section.',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'post_type' => array (
              ),
              'taxonomy' => array (
              ),
              'filters' => array (
                0 => 'search',
              ),
              'elements' => array (
                0 => 'featured_image',
              ),
              'min' => 3,
              'max' => 9,
              'return_format' => 'object',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '592843136e7b4',
          'name' => 'press_section',
          'label' => 'Press Section',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_592843136e7b5',
              'label' => 'Section Title',
              'name' => 'section_title',
              'type' => 'text',
              'instructions' => 'Enter a title for the section.',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_59284a7029ce8',
              'label' => 'Company Logos',
              'name' => 'company_logos',
              'type' => 'gallery',
              'instructions' => 'Upload company logos by clicking "Add to gallery" below.',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'min' => 3,
              'max' => 9,
              'insert' => 'append',
              'library' => 'all',
              'min_width' => '',
              'min_height' => '',
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => '',
              'mime_types' => 'gif,png,svg,webp',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '5928431c6e7b6',
          'name' => 'about_section',
          'label' => 'About Section',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_5928431c6e7b7',
              'label' => 'Section Title',
              'name' => 'section_title',
              'type' => 'text',
              'instructions' => 'Enter a title for the section.',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_592851fd0cae6',
              'label' => 'Section Photo',
              'name' => 'section_photo',
              'type' => 'image',
              'instructions' => 'Upload a photo to use in the section.',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'return_format' => 'array',
              'preview_size' => 'thumbnail',
              'library' => 'all',
              'min_width' => 300,
              'min_height' => 600,
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => '',
              'mime_types' => '',
            ),
            array (
              'key' => 'field_59284b135306a',
              'label' => 'Section Headline',
              'name' => 'section_headline',
              'type' => 'text',
              'instructions' => 'Enter a headline to appear above the section text.',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_59284b2f5306b',
              'label' => 'Section Text',
              'name' => 'section_text',
              'type' => 'wysiwyg',
              'instructions' => 'Add the section text here.',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'text',
              'toolbar' => 'basic',
              'media_upload' => 0,
              'delay' => 0,
            ),
          ),
          'min' => '',
          'max' => '',
        ),
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'page_template',
        'operator' => '==',
        'value' => 'page-templates/home-page.php',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => array (
    0 => 'the_content',
  ),
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_5920800733c36',
  'title' => 'Location Fields',
  'fields' => array (
    array (
      'key' => 'field_59284f08af048',
      'label' => 'Location Price',
      'name' => 'location_price',
      'type' => 'select',
      'instructions' => 'Select the location price.',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        1 => '$',
        2 => '$$',
        3 => '$$$',
        4 => '$$$$',
      ),
      'default_value' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 0,
      'ajax' => 0,
      'return_format' => 'value',
      'placeholder' => '',
    ),
    array (
      'key' => 'field_59284ff3f95d5',
      'label' => 'Location Address',
      'name' => 'location_address',
      'type' => 'google_map',
      'instructions' => 'Enter the location\'s address.',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'center_lat' => '',
      'center_lng' => '',
      'zoom' => '',
      'height' => 275,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'location',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => array (
    0 => 'the_content',
  ),
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_59285300052d6',
  'title' => 'Options Page Fields',
  'fields' => array (
    array (
      'key' => 'field_59285314155ab',
      'label' => 'Brand Logo',
      'name' => 'brand_logo',
      'type' => 'image',
      'instructions' => 'Upload the brand\'s logo here.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => 475,
      'min_height' => 285,
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => 'gif,png,svg,webp',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'post',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_59284c82c1c86',
  'title' => 'Recipe Fields',
  'fields' => array (
    array (
      'key' => 'field_59284cf56f8fb',
      'label' => 'Recipe Photo',
      'name' => 'recipe_photo',
      'type' => 'image',
      'instructions' => 'Upload a photo to use for the recipe.',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => 300,
      'min_height' => 300,
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => 'gif,jpg,jpeg,png,webp',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'recipe',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'acf_after_title',
  'style' => 'seamless',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

endif;